<a href="https://colab.research.google.com/github/AlinaSabitova/Data_analytics_tools-/blob/main/%D0%94%D0%B71_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Worshop 2.1 Numpy
Скачайте этот ноутбук к себе.
Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
Сохраните результат в своём гитхаб репозитории.

# 1. Импортировать numpy и написать версию

In [2]:
import numpy as np

In [ ]:
np.__version__

'1.23.5'

# 2.Создать нулевой вектор размера 10

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#3. Создать вектор заполненный 7-ами размера 7

In [ ]:
np.full((1,7), 7)

array([[7, 7, 7, 7, 7, 7, 7]])

#4. Создать вектор заполненный четными числами от 10 до 100

In [ ]:
arr = np.arange(10, 100)
arr[::2]

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

#5. Создать массив случайных чисел и развернуть его задом наперёд

In [ ]:
arr = np.random.random(10)
print(arr)
arr[::-1]

[0.70069841 0.34377005 0.43933573 0.5300514  0.27477653 0.73059425
 0.65569905 0.75092853 0.0617207  0.39002615]


array([0.39002615, 0.0617207 , 0.75092853, 0.65569905, 0.73059425,
       0.27477653, 0.5300514 , 0.43933573, 0.34377005, 0.70069841])

In [ ]:
arr = np.random.random_sample(10)
print(arr)
arr[::-1]

[0.45244502 0.31658984 0.24948195 0.52465202 0.13349035 0.64620225
 0.26957566 0.4480803  0.51638805 0.28109614]


array([0.28109614, 0.51638805, 0.4480803 , 0.26957566, 0.64620225,
       0.13349035, 0.52465202, 0.24948195, 0.31658984, 0.45244502])

#6. Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [8]:
arr = np.arange(9).reshape(3, 3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#7. Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [9]:
arr = np.eye(4, k=1)
arr

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

#8. Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [10]:
arr = np.full((4,4), 7)
np.fill_diagonal(arr, [1,2,3,4])
arr

array([[1, 7, 7, 7],
       [7, 2, 7, 7],
       [7, 7, 3, 7],
       [7, 7, 7, 4]])

In [11]:
arr = np.diag([1,2,3,4])
arr[arr == 0] = 7
arr

array([[1, 7, 7, 7],
       [7, 2, 7, 7],
       [7, 7, 3, 7],
       [7, 7, 7, 4]])

#9. Создать матрицу размера 5 на 5 заполненную чиcлами от 0 до 4 в строках.

In [12]:
arr = np.zeros((5, 5))
arr += np.arange(5)
arr

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#10. Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [14]:
arr = np.random.randint(0, 100, (10, 10))
print(arr)
arr - arr.mean(axis = 1, keepdims=True)

[[24 14 84 40 76  1 97 39  5 40]
 [78 19 78 41 17 66 71 15  3 26]
 [12 76 88 72 52 57 55  5 36 79]
 [ 6 95 96 88 91 68 56 24 37 85]
 [58 40 42  1 18 34 88  0 63 85]
 [19 65 64  0 73 29 73 34 91 14]
 [19 32 24 22 42 57 21 24 76 91]
 [90 20  5 42 63 20 85 22 93 93]
 [38 58 68 74 84 71 61 56 15 57]
 [23 89 51 63 70  6  4 25 97 18]]


array([[-18. , -28. ,  42. ,  -2. ,  34. , -41. ,  55. ,  -3. , -37. ,
         -2. ],
       [ 36.6, -22.4,  36.6,  -0.4, -24.4,  24.6,  29.6, -26.4, -38.4,
        -15.4],
       [-41.2,  22.8,  34.8,  18.8,  -1.2,   3.8,   1.8, -48.2, -17.2,
         25.8],
       [-58.6,  30.4,  31.4,  23.4,  26.4,   3.4,  -8.6, -40.6, -27.6,
         20.4],
       [ 15.1,  -2.9,  -0.9, -41.9, -24.9,  -8.9,  45.1, -42.9,  20.1,
         42.1],
       [-27.2,  18.8,  17.8, -46.2,  26.8, -17.2,  26.8, -12.2,  44.8,
        -32.2],
       [-21.8,  -8.8, -16.8, -18.8,   1.2,  16.2, -19.8, -16.8,  35.2,
         50.2],
       [ 36.7, -33.3, -48.3, -11.3,   9.7, -33.3,  31.7, -31.3,  39.7,
         39.7],
       [-20.2,  -0.2,   9.8,  15.8,  25.8,  12.8,   2.8,  -2.2, -43.2,
         -1.2],
       [-21.6,  44.4,   6.4,  18.4,  25.4, -38.6, -40.6, -19.6,  52.4,
        -26.6]])

#11. Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца

In [ ]:
arr = np.random.randint(0, 100, (10, 10))
print(arr)
print("Медиана:", np.median(arr, axis=0, keepdims=True))
arr - np.median(arr, axis=0, keepdims=True)

[[18 27 64 48 71 42 17 12 21 99]
 [23 41 99  1 45 64 67 81 26 22]
 [96 29 34 18 22 28  6  8 19 89]
 [77 47 26 54 62 23 65 74 96 22]
 [87 51 89 81 37 91 27 30 13 60]
 [17 64 29 95 11 64 64 81 48 57]
 [62  5 70 22 29 10 60 94 77 92]
 [84 61 68 60 64 26 21 26 25 65]
 [73 57 63 45 61 92 77 87 58 85]
 [32 47 92 82 51 33 54 88  9 63]]
Медиана: [[67.5 47.  66.  51.  48.  37.5 57.  77.5 25.5 64. ]]


array([[-49.5, -20. ,  -2. ,  -3. ,  23. ,   4.5, -40. , -65.5,  -4.5,
         35. ],
       [-44.5,  -6. ,  33. , -50. ,  -3. ,  26.5,  10. ,   3.5,   0.5,
        -42. ],
       [ 28.5, -18. , -32. , -33. , -26. ,  -9.5, -51. , -69.5,  -6.5,
         25. ],
       [  9.5,   0. , -40. ,   3. ,  14. , -14.5,   8. ,  -3.5,  70.5,
        -42. ],
       [ 19.5,   4. ,  23. ,  30. , -11. ,  53.5, -30. , -47.5, -12.5,
         -4. ],
       [-50.5,  17. , -37. ,  44. , -37. ,  26.5,   7. ,   3.5,  22.5,
         -7. ],
       [ -5.5, -42. ,   4. , -29. , -19. , -27.5,   3. ,  16.5,  51.5,
         28. ],
       [ 16.5,  14. ,   2. ,   9. ,  16. , -11.5, -36. , -51.5,  -0.5,
          1. ],
       [  5.5,  10. ,  -3. ,  -6. ,  13. ,  54.5,  20. ,   9.5,  32.5,
         21. ],
       [-35.5,   0. ,  26. ,  31. ,   3. ,  -4.5,  -3. ,  10.5, -16.5,
         -1. ]])

#12. Создать матрицу случайных чисел 5x5. Добавить к ней столбцы максимумов и минимумов по строкам. Получится матрица 5x7.

In [ ]:
arr = np.random.randint(0, 100, (5, 5))
print(arr)
a = arr.min(axis=1, keepdims=True)
b = arr.max(axis=1, keepdims=True)
np.concatenate((arr, a, b), axis=1)

[[99 75 73  3 82]
 [91 73 27 79 72]
 [92  9 48 91 14]
 [14  3 51 51 63]
 [16 62 12  6 99]]


array([[99, 75, 73,  3, 82,  3, 99],
       [91, 73, 27, 79, 72, 27, 91],
       [92,  9, 48, 91, 14,  9, 92],
       [14,  3, 51, 51, 63,  3, 63],
       [16, 62, 12,  6, 99,  6, 99]])

#13. Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрицы. Найти произведение этих матриц. Найти обратную матрицу этого произведения.

In [15]:
arr = np.arange(1, 51)
arr1 = arr[::2]
arr2 = arr[1::2]
print("Вектор нечетных чисел:", arr1)
print("Вектор четных чисел:", arr2)
new_arr1 = arr1.reshape(5, 5)
new_arr2 = arr2.reshape(5, 5)
a = np.dot(new_arr1, new_arr2)
print(a)
try:
  print(np.linalg.inv(a)) # матрица невырожденная, следовательно у нее нет обратной матрицы
except:
  print("Матрица невырожденная, следовательно у нее нет обратной матрицы")

Вектор нечетных чисел: [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]
Вектор четных чисел: [ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]
[[ 750  800  850  900  950]
 [1850 2000 2150 2300 2450]
 [2950 3200 3450 3700 3950]
 [4050 4400 4750 5100 5450]
 [5150 5600 6050 6500 6950]]
Матрица невырожденная, следовательно у нее нет обратной матрицы


#14. Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [ ]:
arr = np.zeros((8,8), dtype=int)
arr[1::2,::2] = 1
arr[::2,1::2] = 1
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
